import { appendFile, open, readFile, unlink } from "node:fs/promises";
import { generateKeyPair, randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import type { ServerConfig } from "./type.js";

const generateRsaKeyPair = promisify(generateKeyPair);

function parseEnv(source: string): Map<string, string> {
    const result = new Map<string, string>();
    for (const line of source.split(/\r?\n/)) {
        const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$/);
        if (match) result.set(match[1]!, match[2]!);
    }
    return result;
}

async function loadEnv(path: string): Promise<void> {
    try {
        for (const [key, value] of parseEnv(await readFile(path, "utf8")))
            if (process.env[key] === undefined) process.env[key] = value;
    } catch (error: unknown) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
}

async function withLock<T>(path: string, work: () => Promise<T>): Promise<T> {
    const lockPath = `${path}.rigged.lock`;
    for (let attempt = 0; attempt < 100; attempt += 1) {
        try {
            const lock = await open(lockPath, "wx");
            try {
                return await work();
            } finally {
                await lock.close();
                await unlink(lockPath).catch(() => undefined);
            }
        } catch (error: unknown) {
            if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
            await new Promise((resolve) => setTimeout(resolve, 50));
        }
    }
    throw new Error(`Timed out waiting for the .env initialization lock at ${lockPath}`);
}

async function appendManaged(path: string, values: Record<string, string>): Promise<void> {
    const lines = Object.entries(values)
        .map(([key, value]) => `${key}=${value}`)
        .join("\n");
    await appendFile(path, `\n# Generated by @slopus/rigged; keep this file secret.\n${lines}\n`, {
        mode: 0o600,
    });
}

/** Loads .env without overriding real environment values and safely bootstraps missing secrets. */
export async function initializeManagedEnvironment(
    configPath: string,
    config: ServerConfig,
): Promise<void> {
    const envPath = join(dirname(configPath), ".env");
    await loadEnv(envPath);
    const needsJwt =
        config.server.role !== "api" &&
        !config.jwt.privateKeyPath &&
        !process.env.RIGGED_JWT_PRIVATE_KEY &&
        !process.env.RIGGED_JWT_PRIVATE_KEY_B64;
    const needsPepper = config.auth.password.enabled && !process.env.RIGGED_PASSWORD_PEPPER;
    const needsIntegrationSecret = !process.env[config.security.integrationSecretEnv];
    if (!needsJwt && !needsPepper && !needsIntegrationSecret) return;

    await withLock(envPath, async () => {
        await loadEnv(envPath);
        const values: Record<string, string> = {};
        if (
            config.server.role !== "api" &&
            !config.jwt.privateKeyPath &&
            !process.env.RIGGED_JWT_PRIVATE_KEY &&
            !process.env.RIGGED_JWT_PRIVATE_KEY_B64
        ) {
            const pair = await generateRsaKeyPair("rsa", {
                modulusLength: 3072,
                publicKeyEncoding: { type: "spki", format: "pem" },
                privateKeyEncoding: { type: "pkcs8", format: "pem" },
            });
            values.RIGGED_JWT_PRIVATE_KEY_B64 = Buffer.from(pair.privateKey).toString("base64");
            values.RIGGED_JWT_PUBLIC_KEY_B64 = Buffer.from(pair.publicKey).toString("base64");
        }
        if (config.auth.password.enabled && !process.env.RIGGED_PASSWORD_PEPPER)
            values.RIGGED_PASSWORD_PEPPER = randomBytes(32).toString("base64url");
        if (!process.env[config.security.integrationSecretEnv])
            values[config.security.integrationSecretEnv] = randomBytes(32).toString("base64url");
        if (Object.keys(values).length) {
            await appendManaged(envPath, values);
            Object.assign(process.env, values);
        }
    });
}
